- file:
    path: docker-compose.yml
    change:
      - old: 1
        new: 1
        highlight: true
        snippet: dockerComposeAddFrankFlow
      - old: 1
        new: 1
        highlight: true
        snippet: dockerComposeAddFrankFlow
      - insert: 6
        highlight: true
        snippet: dockerComposeAddFrankFlow
- snippet:
    name: dockerComposeAddFrankFlow
    markup: none
    context: 50
