- file:
    path: server/configurations/DeploymentSpecifics.properties
    change:
      - insert: 4
        highlight: true
        snippet: openConsole
- snippet:
    name: openConsole
    markup: none
    context: 50
