- file:
    path: docker-compose.yml
    change:
      - old: 1
        new: 1
        highlight: true
        snippet: dummyChangePortForGithubActions
- snippet:
    name: dummyChangePortForGithubActions
    markup: none
    context: 50
