- file:
    path: docker-compose.yml
    change:
      - insert: 1
        highlight: true
        snippet: haveTableIbissource
- snippet:
    name: haveTableIbissource
    markup: none
    context: 50