- file:
    path: docker-compose.yml
    change: add
- file:
    path: server/configurations/Server/Configuration.xml
    change: add
- file:
    path: server/resources/DeploymentSpecifics.properties
    change: add
- file:
    path: server/resources/resources.yml
    change: add
