- predecessor: v500
- file:
    path: client/configurations/Client/Configuration.xml
    change:
      - old: 2
        new: 4
        snippet: useHidden
        highlight: true
- file:
    path: server/configurations/DeploymentSpecifics.properties
    change: del
- file:
    path: server/configurations/Server/Configuration.xml
    change:
      - old: 1
        new: 1
        highlight: true
        snippet: expectCredentialsInUrl
- snippet:
    name: useHidden
    markup: xml
    context: 10
- snippet:
    name: expectCredentialsInUrl
    markup: xml
    context: 10
