- file:
    path: tests/hermesBridge/scenario01.properties
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: useProperty
- file:
    path: classes/StageSpecifics_LOC.properties
    change:
        - insert: 1
          highlight: true
          snippet: defineProperty
- snippet:
    name: useProperty
    markup: none
    context: 50
- snippet:
    name: defineProperty
    markup: none
    context: 50