services:
  custom-logging:
    image: frankframework/frankframework:8.3.0-SNAPSHOT
    ports:
      - 8080:8080
    volumes:
      - ./configurations:/opt/frank/configurations
      - ./my-log4j2.yaml:/opt/frank/my-log4j2.yaml
      - ./my-log4j2.xml:/opt/frank/my-log4j2.xml
      # - ./lib/log4j-core-2.24.0.jar:/usr/local/tomcat/lib/log4j-core-2.24.0.jar
    environment:
      instance.name: custom-logging
      dtap.stage: LOC
      configurations.directory.autoLoad: true
      log4j.configurationFile: log4j4ibis.xml,file:///opt/frank/my-log4j2.yaml
