services:
  frank-docker-example:
    image: frankframework/frankframework:8
    ports:
      - 8080:8080
    volumes:
      - ./configurations:/opt/frank/configurations
      - ./my-log4j2.yaml:/opt/frank/resources/my-log4j2.yaml
    environment:
      instance.name: frank-docker-example
      dtap.stage: LOC
      configurations.directory.autoLoad: true
      log4j.configurationFile: /opt/frank/resources/my-log4j2.yaml
