- predecessor: v480
- file:
    path: src/main/configurations/TransactionsExample/input.xsd
    change: add
- file:
    path: src/main/configurations/TransactionsExample/Configuration.xml
    change:
      - old: 1
        new: 2
        highlight: true
        snippet: toCorrelationId
      - old: 1
        new: 6
        highlight: true
        snippet: toCorrelationId
      - old: 1
        new: 1
        snippet: toCorrelationId
        highlight: true
- snippet:
    name: toCorrelationId
    markup: xml
    context: 5

