services:
  frank-docker-example:
    image: frankframework/frankframework:8
    ports:
      - 8080:8080
    volumes:
      - ./configurations:/opt/frank/configurations
    environment:
      instance.name: frank-docker-example
      dtap.stage: LOC
      configurations.directory.autoLoad: true
      configurations.names: ""
