- file:
    path: docker-compose.yml
    change: add
- file:
    path: src/main/resources/Configuration.xml
    change: add
- file:
    path: src/main/resources/DatabaseChangelog.xml
    change: add
- file:
    path: src/main/resources/DeploymentSpecifics.properties
    change: add
- file:
    path: src/main/resources/resources.yml
    change: add
