- file:
    path: docker-compose.yml
    change: add
- file:
    path: Dockerfile
    change: add
- file:
    path: src/main/configurations/TransactionsExample/Configuration.xml
    change: add
- file:
    path: src/main/configurations/TransactionsExample/DatabaseChangelog.xml
    change: add
- file:
    path: src/main/resources/DeploymentSpecifics.properties
    change: add
- file:
    path: src/main/resources/resources.yml
    change: add
