services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testiaf_user00
      POSTGRES_USER: testiaf_user
      POSTGRES_DB: testiaf
      max_prepared_transactions: 100
  jms:
    image: apache/activemq-artemis:2.36.0
    ports:
      - 8160:8160
      - 61616:61616
    environment:
      ANONYMOUS_LOGIN: true
  ff:
    image: frankframework/frankframework:latest
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources:/opt/frank/resources
    environment:
      jdbc.hostname: db
      jms.hostname: jms
      transactionmanager.type.default: NARAYANA
      jms.createDestination: true
