- file:
    path: build.xml
    change: add
- file:
    path: restart.bat
    change: add
- file:
    path: .gitignore
    change: add
- file:
    path: classes/DeploymentSpecifics.properties
    change: add
- file:
    path: configurations/Conclusion/conclusion2mundo.xslt
    change: add
- file:
    path: configurations/Conclusion/Configuration.xml
    change: add
- file:
    path: configurations/Conclusion/StageSpecifics_DEV.properties
    change: add
- file:
    path: configurations/Conclusion/StageSpecifics_LOC.properties
    change: add
- file:
    path: configurations/Conclusion/xmlInput.xsd
    change: add
- file:
    path: tests/Conclusion/badRequest.txt
    change: add
- file:
    path: tests/Conclusion/common.properties
    change: add
- file:
    path: tests/Conclusion/expectedMessageToMundo.xml
    change: add
- file:
    path: tests/Conclusion/invalid.txt
    change: add
- file:
    path: tests/Conclusion/invalid.xml
    change: add
- file:
    path: tests/Conclusion/ok.txt
    change: add
- file:
    path: tests/Conclusion/refToInvalid.txt
    change: add
- file:
    path: tests/Conclusion/refToValid.txt
    change: add
- file:
    path: tests/Conclusion/scenario01.properties
    change: add
- file:
    path: tests/Conclusion/scenario02.properties
    change: add
- file:
    path: tests/Conclusion/valid.txt
    change: add
- file:
    path: tests/Conclusion/valid.xml
    change: add
