services:
  frank-authorization-client:
    image: frankframework/frankframework:8.3.0-SNAPSHOT
    ports:
      - 8080:8080
    volumes:
      - ./client/configurations:/opt/frank/configurations
    environment:
      instance.name: frank-authorization-client
      dtap.stage: LOC
      configurations.directory.autoLoad: true
  frank-authorization-server:
    image: frankframework/frankframework:8.3.0-SNAPSHOT
    ports:
      - 8081:8080
    volumes:
      - ./server/configurations:/opt/frank/configurations
    environment:
      instance.name: frank-authorization-server
      dtap.stage: DEV
      configurations.directory.autoLoad: true
      application.security.http.transportGuarantee: none
