- predecessor: v500
- file:
    path: src/main/webapp/WEB-INF/web.xml
    change: add
- file:
    path: src/main/webapp/index.html
    change: add
- file:
    path: pom.xml
    change:
      - insert: 1
        snippet: pomPackaging
        highlight: true
      - insert: 6
        snippet: pomDepBuild
        highlight: true
      - insert: 9
        snippet: pomDepBuild
        highlight: true
- file:
    path: src/main/java/org/frankframework/maven/webapp/example/Main.java
    change:
      - old: 7
        new: 12
        snippet: java
- snippet:
    name: pomPackaging
    markup: xml
    context: 3
- snippet:
    name: pomDepBuild
    markup: xml
    context: 3
- snippet:
    name: java
    markup: none
    context: 50
