- file:
    path: build.xml
    change: add
- file:
    path: restart.bat
    change: add
- file:
    path: configurations/NewHorizons/Configuration.xml
    change: add
- file:
    path: configurations/NewHorizons/DatabaseChangelog.xml
    change: add
- file:
    path: configurations/NewHorizons/StageSpecifics_LOC.properties
    change: add
