- file:
    path: configurations/NewHorizons/booking.xsd
    change: add
- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - insert: 13
          highlight: true
          snippet: addPipeline
- snippet:
    name: addPipeline
    markup: xml
    context: 50